title: "Artist Portfolio"
email: "artist@example.com"
description: "A portfolio showcasing the artwork of Asjad Faraz."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: "artist"
github_username:  "artist"
theme: minima

collections:
  artworks:
    output: true
